More UI updates
airiusc/policy-management pull request #60
Opened 2022-12-08 03:02 UTC by kaitlinnnn

Good evening _Joseph_,

**Good news:** I added more information text to the login and welcome pages and the login page is now ultra wide responsive!

**Bad news:** I couldn't figure out a nicer way to write the code for the Google button because on xs, sm, and xl screens the Google button needs to be centered within the col, but on md and lg screens the Google button needs to be aligned left. 

if you think there's a better way to do that please let me know. i did some research, but there isn't a lot of information about responsiveness for xl screen sizes.

regards,
kaitlin

**p.s.** i also didn't make any changes to the drawer menu or the quasar notifications, but i did ask some questions under issue #51

2022-12-08 08:29 UTC, jbcallv requested changes
this shows how wide they look rn ik u can't like rly test it bc u don't have ultrawide is okay
![image](https://user-images.githubusercontent.com/67614219/206397135-b26b4f40-b5f2-4690-85b1-37bca5927465.png)

2022-12-08 08:29 UTC, jbcallv commented on src/pages/auth/LoginPage.vue
> +        <div class="col-10 col-md-6">
i think the text might appear to be grouped better if on ultrawide it still spanned two lines. If u think so too, we should add a xl col of size 3 or 4

2022-12-08 08:29 UTC, jbcallv commented on src/pages/auth/LoginPage.vue
> +        <div class="col-10 col-md-3 col-xl-6">
when i made the page fullscreen col-xl-6 was reallllyyyyy big. Let's shrink it down to xl-2

2022-12-08 08:29 UTC, jbcallv commented on src/pages/auth/LoginPage.vue
> +            <div class="col-12 col-xl-3">
and we should remove xl-3 here so the button is as wide as the inputs

2022-12-08 08:29 UTC, jbcallv commented on src/pages/auth/LoginPage.vue
> +              <img src="/icons/btn_google.png" height="46" width="191" />
is there a difference in these three? /gen

2022-12-08 18:15 UTC, kaitlinnnn commented on src/pages/auth/LoginPage.vue
> +        <div class="col-10 col-md-6">
i tried testing for ultra wide by stretching out my browser window, but i couldn't really look at it that well because i could only see half the site at a time. sooo the pic is very helpful. i'll make all of the col sizes smaller for xl screen sizes

2022-12-08 18:16 UTC, kaitlinnnn commented on src/pages/auth/LoginPage.vue
> +        <div class="col-10 col-md-3 col-xl-6">
# **_k_**

2022-12-08 18:17 UTC, kaitlinnnn commented on src/pages/auth/LoginPage.vue
> +            <div class="col-12 col-xl-3">
i thought it looked strange when the screen size was large and the button was really long,, but if you prefer that then i'll remove it bc i won't have to look at it

2022-12-08 18:31 UTC, kaitlinnnn commented on src/pages/auth/LoginPage.vue
> +              <img src="/icons/btn_google.png" height="46" width="191" />
this is the part i was talking about in the bad news section of the pr description. i'll try to explain it more clearly:

1. the first div and button has `class="row justify-center lt-md"`
this centers the Google login button on screen sizes less than medium (so small and extra small) because the content is all stacked

2. the second div and button has `class="row lt-xl gt-sm"`
this leaves the Google login button justified left on screen sizes less than extra large and greater than small (so medium and large) because the content is in three separate columns instead of stacked

3. the third div and button has `class="row justify-center xl"`
this centers the Google login button on extra large screen size because the page content is all stacked instead 

i tried a few different ways to combine the 1st and 3rd div by adding `class="row justify-center lt-md gt-lg"`, but this doesn't work because a screen size can't fit both of those requirements at once

if you know of a way to simplify this more or a different method to use pls let me know.

the problem i was trying to solve w this code: 
- row content needs to be centered on small, extra small, and extra large screens
- row content needs to NOT be centered on medium and large screens

2022-12-08 18:46 UTC, davidy-airius commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx AST – Scan Summary & Details** – [90361f33\-943d\-4250\-a74d\-ebce5981c39f](https://ast.checkmarx.net/projects/742e7fda-eccc-4c3c-9fd8-24fa8b944e7c/scans?id=90361f33-943d-4250-a74d-ebce5981c39f&branch=more-ui-updates)
### No New Or Fixed Issues Found

2022-12-08 21:29 UTC, kaitlinnnn commented
Do any of the other pages need to be specially formatted for XL screen sizes?

2022-12-09 01:59 UTC, davidy-airius commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx AST – Scan Summary & Details** – [dbb017a7\-8055\-43ce\-bb63\-db5a85c4ddaa](https://ast.checkmarx.net/projects/742e7fda-eccc-4c3c-9fd8-24fa8b944e7c/scans?id=dbb017a7-8055-43ce-bb63-db5a85c4ddaa&branch=more-ui-updates)
### No New Or Fixed Issues Found

2022-12-09 01:59 UTC, kaitlinnnn commented
I increased the size of the Google login button because it seemed small in comparison to the text inputs and regular login button. The Google login button looks slightly grainy to me now, so lmk what you think the best move is

2022-12-09 08:36 UTC, jbcallv approved these changes

2022-12-09 08:36 UTC, merged